### PR TITLE
Refactor templates to not use `pillar.get`

### PR DESCRIPTION
**Pull request by sticky-note**
### PR progress checklist (to be filled in by reviewers)

- [ ] Changes to documentation are appropriate (or tick if not required)
- [ ] Changes to tests are appropriate (or tick if not required)
- [ ] Reviews completed

---

#### Primary type

- [ ] `[build]`    Changes related to the build system
- [ ] `[chore]`    Changes to the build process or auxiliary tools and libraries such as documentation generation
- [ ] `[ci]`       Changes to the continuous integration configuration
- [ ] `[feat]`     A new feature
- [ ] `[fix]`      A bug fix
- [ ] `[perf]`     A code change that improves performance
- [x] `[refactor]` A code change that neither fixes a bug nor adds a feature
- [ ] `[revert]`   A change used to revert a previous commit
- [ ] `[style]`    Changes that do not affect the meaning of the code (white-space, formatting, missing semi-colons, etc.)

#### Secondary type

- [ ] `[docs]`     Documentation changes
- [x] `[test]`     Adding missing or correcting existing tests

### Does this PR introduce a `BREAKING CHANGE`?

No.

### Related issues and/or pull requests

#44 #45

### Describe the changes you're proposing

Refactor templates to not use `pillar.get`

### Documentation checklist

- [ ] Updated the `README` (e.g. `Available states`).
- [ ] Updated `pillar.example`.

### Testing checklist

- [ ] Included in Kitchen (i.e. under `state_top`).
- [ ] Covered by new/existing tests (e.g. InSpec, Serverspec, etc.).
- [ ] Updated the relevant test pillar.

### CODE REVIEW

**Comment by myii** [comment]
@sticky-note Now that #45 is merged, we can look at adjusting the functionality -- please rebase this PR on top of the latest version of this formula.

If you want to replace `pillar.get` here, then you'll need to reintroduce the block that was taken out of `map.jinja` during #45.  That's if you need the rest of the pillar merged into the map, meaning that the pillar `lookup` is not enough to work properly here.

**Comment by myii** [comment]
@sticky-note Just to be clear, if you also merge the rest of the pillar into the map, all of the Travis instances will fail but that's expected, because the `yaml_dump` InSpec tests will need to be updated to mirror the new entries that are coming in from the pillar.  If it doesn't make sense, just make the changes and I'll look at how the InSpec tests need to be updated accordingly.

**Comment by sticky-note** [comment]
@myii Do we need to do a breaking change then ?

**Comment by myii** [comment]
@sticky-note Probably not.  I've already identified some problems with the existing tests, which is why this PR didn't fail anything!  I'll try to get back to you within the day.

**Comment by myii** [comment]
@sticky-note OK, I've added some commits and force pushed this so that it uses the latest tests.  One benefit is showing us how the files have changed before and after this PR.

* https://github.com/saltstack-formulas/dhcpd-formula/pull/46/commits/880b2815ee8102904b6586ded0d1e81412458575#diff-0fd1b60feac2145ce715c2b2f67c9ae4
  - This shows us how the managed `dhcpd.conf` file changes after this PR, across all platforms
  - Do you want to fix this ordering so that there are no changes for end users?  If not, this is ready to be merged, with the tests updated for the current state.
* Actually, it was these tests that initially confirmed that your method requires the whole pillar to be merged on top of the pillar `lookup`, which I added in 4baed92.
* The tests for checking the output of `map.jinja` have also been updated, since the pillar is now being merged in.  Those changes can be seen in 174e8d2.

Once we're finalised with this PR, we can look at rebasing #44 and then fixing all of the tests to confirm everything is working as defined by the tests.

**Comment by sticky-note** [comment]
@Myii I think ordering is okay

**Comment by myii** [comment]
> @myii I think ordering is okay

OK, merged.

In terms of #44, please go ahead and rebase and look forward to all of the failing tests!  Do you want to fix the tests yourself?

**Pull request merged**
