### PR TITLE
Add host-name option to client configuration

### PR DESCRIPTION
**Pull request by mattwillsher**
This PR adds the host-name option for DHCP client requests

### CODE REVIEW

**Comment by mattwillsher** [comment]
The PR was a bit premature - I've still to double check a couple of parts. I'll update again when ready.

**Comment by gravyboat** [comment]
Thanks for the note @mattwillsher, are you going to add an example in the map?

**Comment by mattwillsher** [comment]
Yes, will do @gravyboat, good catch. I've got the code working now, will add the docs and update the PR in the next day or so.

**Comment by mattwillsher** [comment]
Turn out I had the time now :)

Sorry for the large number of commits for such a small change. I can squash if you want.

**Comment by babilen** [comment]
Squashing would be great, yeah

**Comment by mattwillsher** [comment]
Done @babilen

**Comment by gravyboat** [comment]
Thanks @mattwillsher! Good changes.

**Pull request merged**
