### PR TITLE
Add support for several config options

### PR DESCRIPTION
**Pull request by kiwiz**
New:

- key
- router
- update-static-leases
- subnet-mask
- ddns-domainname
- use-host-decl-names

Updated:

- allow/deny - Allow passing an array of values like so:
```
  deny:
    - bootp
    - client-updates
    - declines
    - leasequery
```

### CODE REVIEW

**Comment by kiwiz** [comment]
Thanks for the review. :]

I've split out the formatting changes into a separate commit (e5e39be). W.r.t. the allow/deny changes, dhcpd was giving me an error if the clause wasn't in the pool block.

**Comment by 0xf10e** [comment]
Ah, OK. Did I miss the mention of moving accept/deny into the pool-part of the template? ;)

**Comment by kiwiz** [comment]
Fixed up & split an unrelated change into a separate commit.

**Comment by 0xf10e** [comment]
:+1:

**Comment by aboe76** [comment]
@kiwiz thanks for this

**Comment by kiwiz** [comment]
:+1:

**Pull request merged**
